import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fileverse/ui/styles';
import { EnsPagePrivyProvider } from "@/components/privy/ens-page-privy-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><EnsPagePrivyProvider>{children}</EnsPagePrivyProvider></body>
    </html>
  );
}
